### ISSUE TITLE
Metadata: deploy() not supported

### ISSUE THREAD

**Issue by mjmartin** [developerforce/Force.com-Toolkit-for-PHP#19]
Please can you support the deploy() call.

**Comment by AkhileshDahat** [comment]
Hello Pat,
  
 This Is the awesome toolkit for the PHP , but currently i am having the requirement for building the web app.So it can create the triggers and classes by php into salesforce. Can you please provide the appropriate guideline for this.This would be great if the toolkit is having such functionality.

**Comment by metadaddy-sfdc** [comment]
The PHP toolkit only supports the SOAP API. You should look into the [Tooling API](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/) - it should be straightforward to use curl in PHP to create Apex code via the Tooling API with REST.
