### ISSUE TITLE
SoapClient TLS

### ISSUE THREAD

**Issue by aaronbauman** [developerforce/Force.com-Toolkit-for-PHP#35]
Does SforceBaseClient need to be updated in light of POODLE vulnerability and Salesforce dropping SSL support?

I cannot find any good resource on how to instantiate PHP SoapClient to use only TLS instead of SSL.

**Comment by jithendraKoduru** [comment]
Hi Pat, Now that Salesforce would be disabling TLS1.0 in 2016, would the SoapClient in PHP developer tool kit automatically negotiate TLS1.1 or higher, when making inbound calls to Salesforce, or do we have to upgrade the toolkit.

**Comment by metadaddy-sfdc** [comment]
@jithendraKoduru Yes - the TLS negotiation is a feature of PHP/OpenSSL, not directly under the control of the toolkit. If your PHP deployment currently supports TLS1.1, then I'm pretty sure it's already negotiating 1.1 in preference to 1.0, and will continue to run unchanged when we turn off 1.0.

You can use phpinfo to see what version of OpenSSL PHP is using, and from there figure out whether it has TLS1.1:

**phpinfo.php:**

    <?php
    phpinfo();
    ?>

Example output (in curl section):

> SSL Version	OpenSSL/1.0.1q

You'll need OpenSSL 1.0.1 or higher for TLS1.1.

**Comment by albertocubeddu** [comment]
Seems that is not automatic updating. I will have a debug tomorrow and If I find a solution I gonna post here :)

**Comment by MeuhMeuh** [comment]
@albertocubeddu any update ? :)
