### ISSUE TITLE
Broken queries with LIMIT 1

### ISSUE THREAD

**Issue by jp7carlos** [developerforce/Force.com-Toolkit-for-PHP#44]
This commit from 2012 broke queries with LIMIT 1:
https://github.com/developerforce/Force.com-Toolkit-for-PHP/commit/489650583ab8bf945306147aaa48933bc3680658

It pushes $record when there is no $record variable defined.

**Comment by metadaddy-sfdc** [comment]
What's the exact error you're seeing? Just want to make sure I fix the right thing!

**Comment by jp7carlos** [comment]
I was updating the Force.com library from a very old version to current version. And we used LIMIT 1 to get the first result of a query. I'm not sure if the problem happens because I have an outdated version of the WSDL. 

But you can see in the source code that there is no variable $record at that point, because $record is created during the foreach ($response->records as $record), and this loop only runs if $response->records is Array. But what i get when i use "LIMIT 1" is a $response->records which is a single object, not an array of records, just properties of a single record.

**Comment by metadaddy-sfdc** [comment]
That's odd - the 'else' branch is never executed when I run it, probably because we select the `SOAP_SINGLE_ELEMENT_ARRAYS` feature when we create the SOAP client.

What version of PHP are you running? What do you see when you do this after the query:

	echo "getLastRequest()\n";
	echo $connection->getLastRequest();
	echo "\n";

	echo "getLastResponse()\n";
	echo $connection->getLastResponse();
	echo "\n";

**Comment by jp7carlos** [comment]
It seems it had to do with SOAP_SINGLE_ELEMENT_ARRAYS. 
My code was creating it's own SoapClient without it, due to some customization that's not needed anymore. 
I removed my code and i'm using yours now. It seems to be OK. 
Sorry to bother you and thanks for your help.
