### ISSUE TITLE
SoapFault: INVALID_TYPE: Must send a concrete entity type.

### ISSUE THREAD

**Issue by Randagio13** [developerforce/Force.com-Toolkit-for-PHP#58]
Hi guys,

with PHP7, I tried to create a Lead but return back this error: SoapFault: INVALID_TYPE: Must send a concrete entity type.

Any ideas?

Let me know.

Thanks in advance.

**Comment by winternet-studio** [comment]
I have the same issue trying to create Contact records with PHP7. Found that this issue is talking about the same thing: https://github.com/developerforce/Force.com-Toolkit-for-PHP/issues/47 - and a solution is found here: https://github.com/developerforce/Force.com-Toolkit-for-PHP/pull/48/files
