### ISSUE TITLE
Access Files module

### ISSUE THREAD

**Issue by tekoyaki** [developerforce/Force.com-Toolkit-for-PHP#80]
Is there a way to access the new-ish Files module that replaced Notes & Attachments using the SOAP API? I cannot seem to find the module on [the docs](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_list.htm). Or is the change simply on the force.com side and backend is all the same, still using [Attachment](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_attachment.htm)?

**Comment by Saaha** [comment]
Hello,
Actually, it's on Salesforce side, the only thing you need to *maybe* update is the wsdl and create connection with a recent one. 
See [SOAP API Developer Guide - Attachment](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_attachment.htm)

Edit: Tired, I missred your comment. I think there is no File object accessible with Soap. It seems for some objects, there is a middle implementation and with Soap you need to continue with old Object but with Apex code you can use newest Object.

**Comment by tekoyaki** [comment]
Thanks.

After reading a lot of release notes and posts, I found that the "Files" module is actually named "ContentDocument" in force.com, and "Files" in Salesforce Chatter: https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contentdocument.htm
